### ISSUE TITLE
the generator of TrtFP16, its accuracy drops seriously

### ISSUE THREAD

**Issue by ZhangLei999** [foocker/SadTalkerTriton#2]
Great work!
I tried but failed because of its accuracy.
The generator of TrtFP32 is normal. 
After   command like this :
"trtexec --onnx=generator_sim.onnx --saveEngine=generator.engine --fp16".
FP16 model can no longer be used.

**Comment by ZhangLei999** [comment]
I checked the parameters,  and some exceed FP16 maximum.

**Comment by Nice-try-zzw** [comment]
#3 May I ask if you encountered this problem while generating the model? How can you handle it? thanks!

**Comment by ZhangLei999** [comment]
TensorRT-8.6.1.6      
nvidia Geforce 2080ti

**Comment by ZhangLei999** [comment]
> > I checked the parameters, and some exceed FP16 minimum.
> 
> i have only test for onnx, and g to int8 engine drops a lot. fp16 engine, maybe work fine(trt8.6.1)? your trt version is ?

I also test for onnxruntime, and the result is the same.
My test code is that:
import onnxruntime
import torch
from model import OcclusionAwareSPADEGenerator,SameBlock2d,DownBlock2d,ResBlock3d,SPADEDecoder

sess_options = onnxruntime.SessionOptions()
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_EXTENDED

generator = onnxruntime.InferenceSession('./model.onnx', sess_options, providers=[('TensorrtExecutionProvider', \
            {'trt_fp16_enable': True, 'trt_engine_cache_enable': True, 'trt_engine_cache_path': './cache'}), 'CUDAExecutionProvider'])

model = torch.load('model.pth').cuda()
model.eval()
source_image = torch.ones(1, 3, 256, 256).cuda()
kp_driving = torch.ones(1, 15, 3).cuda()
kp_source = torch.ones(1, 15, 3).cuda()
torch_out = model(source_image, kp_driving, kp_source)  

onnx_out = generator.run(None, {'source_image':source_image.cpu().numpy(), 'kp_driving':kp_driving.cpu().numpy(),'kp_source':kp_source.cpu().numpy()})[0]
print(torch_out.cpu().data-onnx_out)

**Comment by ZhangLei999** [comment]
Print logs：

tensor([[[[ 0.0179,  0.0032,  0.0024,  ...,  0.0652,  0.1010,  0.1868],
          [ 0.0167,  0.0025,  0.0017,  ...,  0.0686,  0.1020,  0.1584],
          [ 0.0075,  0.0022,  0.0024,  ...,  0.0235,  0.0754,  0.1430],
          ...,
          [ 0.0760,  0.0237,  0.0197,  ...,  0.0291,  0.0411,  0.0668],
          [ 0.1325,  0.0608,  0.0641,  ..., -0.0073,  0.0115,  0.1934],
          [ 0.2221,  0.1697,  0.1617,  ...,  0.1205,  0.1585,  0.3480]],

         [[ 0.0187,  0.0028,  0.0091,  ...,  0.1411,  0.1612,  0.2290],
          [ 0.0207,  0.0162,  0.0094,  ...,  0.0902,  0.0983,  0.1757],
          [ 0.0407,  0.0134,  0.0135,  ...,  0.0451,  0.0527,  0.2198],
          ...,
          [ 0.0764,  0.0257,  0.0971,  ...,  0.0893,  0.0203,  0.1253],
          [ 0.0900,  0.0269,  0.0209,  ..., -0.0101,  0.0148,  0.0852],
          [ 0.1654,  0.1556,  0.1502,  ...,  0.1684,  0.1109,  0.2505]],

         [[ 0.0140,  0.0006, -0.0005,  ...,  0.0881,  0.0518,  0.1277],
          [ 0.0004, -0.0053, -0.0048,  ...,  0.0846,  0.0785,  0.0916],
          [ 0.0035, -0.0067, -0.0011,  ...,  0.0549,  0.0815,  0.1297],
          ...,
          [ 0.0892,  0.0946,  0.0994,  ...,  0.0798,  0.0618,  0.0512],
          [ 0.1316,  0.0334,  0.1115,  ...,  0.0174,  0.0361,  0.0793],
          [ 0.1968,  0.1622,  0.1395,  ...,  0.0635,  0.0858,  0.1624]]]])

**Comment by ZhangLei999** [comment]
If 'trt_fp16_enable' is set to False, the print logs:

tensor([[[[ 0.0000e+00, -1.1921e-07,  5.9605e-08,  ...,  1.1921e-07,
            1.1921e-07,  1.1921e-07],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            1.1921e-07,  5.9605e-08],
          [ 0.0000e+00,  0.0000e+00, -1.1921e-07,  ...,  0.0000e+00,
            1.7881e-07,  4.7684e-07],
          ...,
          [ 1.1921e-07,  0.0000e+00,  0.0000e+00,  ..., -2.3842e-07,
           -1.7881e-07, -5.9605e-08],
          [ 1.7881e-07,  2.3842e-07,  0.0000e+00,  ..., -1.7881e-07,
           -3.5763e-07,  1.1921e-07],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -1.7881e-07,
           -5.9605e-08,  1.1921e-07]],

         [[-1.1921e-07, -1.1921e-07,  0.0000e+00,  ...,  1.1921e-07,
            3.5763e-07,  5.9605e-08],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            2.3842e-07,  4.7684e-07],
          [-1.1921e-07, -1.7881e-07, -1.1921e-07,  ...,  2.3842e-07,
            4.7684e-07,  1.0133e-06],
          ...,
          [-2.9802e-07, -6.5565e-07, -6.5565e-07,  ...,  0.0000e+00,
           -2.3842e-07,  0.0000e+00],
          [-1.7881e-07, -5.9605e-07, -5.3644e-07,  ..., -2.3842e-07,
           -1.1921e-07,  1.1921e-07],
          [-2.3842e-07, -2.3842e-07, -3.5763e-07,  ..., -1.1921e-07,
           -1.1921e-07,  0.0000e+00]],

         [[-1.1921e-07, -1.1921e-07, -1.1921e-07,  ..., -5.9605e-08,
            0.0000e+00,  5.9605e-08],
          [-1.1921e-07, -1.1921e-07, -2.3842e-07,  ..., -1.1921e-07,
           -1.1921e-07, -5.9605e-08],
          [-2.9802e-07, -1.7881e-07, -3.5763e-07,  ..., -1.1921e-07,
            0.0000e+00,  2.3842e-07],
          ...,
          [-4.1723e-07, -4.1723e-07, -9.5367e-07,  ..., -5.3644e-07,
           -3.5763e-07, -1.1921e-07],
          [-5.9605e-07, -3.5763e-07, -5.3644e-07,  ..., -2.3842e-07,
           -1.7881e-07, -5.9605e-08],
          [-4.1723e-07, -7.7486e-07, -6.5565e-07,  ..., -2.3842e-07,
           -1.1921e-07, -1.1921e-07]]]])

**Comment by foocker** [comment]
> If 'trt_fp16_enable' is set to False, the print logs:
> 
> tensor([[[[ 0.0000e+00, -1.1921e-07, 5.9605e-08, ..., 1.1921e-07, 1.1921e-07, 1.1921e-07], [ 0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.1921e-07, 5.9605e-08], [ 0.0000e+00, 0.0000e+00, -1.1921e-07, ..., 0.0000e+00, 1.7881e-07, 4.7684e-07], ..., [ 1.1921e-07, 0.0000e+00, 0.0000e+00, ..., -2.3842e-07, -1.7881e-07, -5.9605e-08], [ 1.7881e-07, 2.3842e-07, 0.0000e+00, ..., -1.7881e-07, -3.5763e-07, 1.1921e-07], [ 0.0000e+00, 0.0000e+00, 0.0000e+00, ..., -1.7881e-07, -5.9605e-08, 1.1921e-07]],
> 
> ```
>      [[-1.1921e-07, -1.1921e-07,  0.0000e+00,  ...,  1.1921e-07,
>         3.5763e-07,  5.9605e-08],
>       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
>         2.3842e-07,  4.7684e-07],
>       [-1.1921e-07, -1.7881e-07, -1.1921e-07,  ...,  2.3842e-07,
>         4.7684e-07,  1.0133e-06],
>       ...,
>       [-2.9802e-07, -6.5565e-07, -6.5565e-07,  ...,  0.0000e+00,
>        -2.3842e-07,  0.0000e+00],
>       [-1.7881e-07, -5.9605e-07, -5.3644e-07,  ..., -2.3842e-07,
>        -1.1921e-07,  1.1921e-07],
>       [-2.3842e-07, -2.3842e-07, -3.5763e-07,  ..., -1.1921e-07,
>        -1.1921e-07,  0.0000e+00]],
> 
>      [[-1.1921e-07, -1.1921e-07, -1.1921e-07,  ..., -5.9605e-08,
>         0.0000e+00,  5.9605e-08],
>       [-1.1921e-07, -1.1921e-07, -2.3842e-07,  ..., -1.1921e-07,
>        -1.1921e-07, -5.9605e-08],
>       [-2.9802e-07, -1.7881e-07, -3.5763e-07,  ..., -1.1921e-07,
>         0.0000e+00,  2.3842e-07],
>       ...,
>       [-4.1723e-07, -4.1723e-07, -9.5367e-07,  ..., -5.3644e-07,
>        -3.5763e-07, -1.1921e-07],
>       [-5.9605e-07, -3.5763e-07, -5.3644e-07,  ..., -2.3842e-07,
>        -1.7881e-07, -5.9605e-08],
>       [-4.1723e-07, -7.7486e-07, -6.5565e-07,  ..., -2.3842e-07,
>        -1.1921e-07, -1.1921e-07]]]])
> ```
when you exported onnx, you can do:
```
np.testing.assert_allclose(output[0], torch_output.detach().numpy(), rtol=1e-03, atol=1e-05)
# or 
torch.testing.assert_allclose(torch.tensor(output[0]), torch_output, rtol=1e-03, atol=1e-05)
```
for g.onnx, rtol=1e-01, atol=1e-1 or atol=1.
if the video from the infer(render) is ok, g will be ok.

**Comment by ZhangLei999** [comment]
Thanks for your reply.
I followed your suggestion and the code is as follows:
`np.testing.assert_allclose(onnx_out[0], torch_out.detach().cpu().numpy()[0], rtol=1e-01, atol=1e-1)`

The logs:
`AssertionError: 
Not equal to tolerance rtol=0.1, atol=0.1

Mismatched elements: 64993 / 196608 (33.1%)
Max absolute difference: 1.
Max relative difference: 2.9789724e+38
 x: array([[[3.432617e-01, 3.793945e-01, 2.836914e-01, ..., 1.778564e-01,
         2.037354e-01, 2.333984e-01],
        [2.619629e-01, 4.030762e-01, 3.090820e-01, ..., 1.749268e-01,...
 y: array([[[2.197516e-01, 3.844203e-01, 3.759863e-01, ..., 1.760544e-01,
         2.821431e-01, 2.736730e-01],
        [1.492224e-01, 3.222925e-01, 1.743989e-01, ..., 1.612102e-01,...`

**Comment by ZhangLei999** [comment]
If atol is set to 1, both outputs are close.
The resulting video is of poor quality.
If there is a problem exporting the ONNX model？But why is there no problem with the FP32 version?

**Comment by NingRC** [comment]
![serfwe](https://github.com/foocker/SadTalkerTriton/assets/48577874/452f9dbb-8636-4906-896f-db581e717cdf)
Why is the output of my model not aligned after conversion? Can you help me?

**Comment by ZhangLei999** [comment]
> > If atol is set to 1, both outputs are close. The resulting video is of poor quality. If there is a problem exporting the ONNX model？But why is there no problem with the FP32 version?
> 
> yes, when pt to onnx fp16 is poor, your must check some layers which error are big.

About this, can you give me some suggestion?
I found that at the beginning of the network, the error is very serious.

**Comment by foocker** [comment]
> > > If atol is set to 1, both outputs are close. The resulting video is of poor quality. If there is a problem exporting the ONNX model？But why is there no problem with the FP32 version?
> > 
> > 
> > yes, when pt to onnx fp16 is poor, your must check some layers which error are big.
> 
> About this, can you give me some suggestion? I found that at the beginning of the network, the error is very serious.

hava you replace some function as the closed issue?

**Comment by foocker** [comment]
see the newset update.

**Comment by ZhangLei999** [comment]
Thanks  for your sharing!
