### ISSUE TITLE
Alternative weights download link

### ISSUE THREAD

**Issue by DmitriyVahrushev** [foocker/SadTalkerTriton#4]
Hello! 
Impressive work! Unfortunately, it is pretty hard to download weights for people not from China, because Baidu requires a Chinese mobile number. Would you mind uploading weights.zip to some alternative hosting, e.g. Google Drive?

**Comment by foocker** [comment]
> Hello! Impressive work! Unfortunately, it is pretty hard to download weights for people not from China, because Baidu requires a Chinese mobile number. Would you mind uploading weights.zip to some alternative hosting, e.g. Google Drive?

updated.

**Comment by DmitriyVahrushev** [comment]
Thank you!
